### ISSUE TITLE
Exposing session object signals for user login/logout

### ISSUE THREAD

**Issue by miladhashemi** [os-js/osjs-server#47] opened 2021-01-02 18:16 UTC
Hi Anders,
Last night you added two signal. In server If all of session(not only user) accessed, could provides more general solution. Because at moment it returns only user session.

**Comment by andersevenrud** [comment] 2021-01-02 18:28
Sorry, but I don't understand what you're asking here.

I added two signals, both of which gets the user session data as a parameter.

**Comment by mahsashadi** [comment] 2021-01-02 19:30
Hi.
We are working at the same project.

The parameter in these signals is user profile stored in session (including id, name, usename, groups). It is the object which is returned from login function in authentication Service provider. 

We need to have the whole session object which we stored some other data in it during login process

**Comment by andersevenrud** [comment] 2021-01-02 22:18
> We need to have the whole session object which we stored some other data in it during login process

Sorry, but I still don't understand this.


>  is the object which is returned from login function in authentication Service provider

Yes. Which is the "whole" object.

Can you give an example maybe ?

**Comment by miladhashemi** [comment] 2021-01-03 04:16
> Can you give an example maybe ?
We store to general (key-value) in session. it's below:
```js
session: {
      user: {
        id: 'someId',
        name: 'someName',
        username: 'someUsername',
        group: 'admin',
        projects: ['test', 'test1']
      },
      swiftAuth: {
        ...
      }
    }
```
at server side we need both keys, but in client we need just **user** key!

**Comment by andersevenrud** [comment] 2021-01-03 15:01
Okay. I can change this so that  you get the entire session, not just the user.

> Moreover, we need to extend session object which is not accessable, since parameter is sent via Object.freeze() (in server).

Mutating the session data outside the auth handler like this sounds like a really bad idea. Why do you need to do this ?

**Comment by miladhashemi** [comment] 2021-01-03 15:12
I want to add project list to user session.
> projects: ['test', 'test1']
To get project list, I need some data that we kept them in swiftAuth

**Comment by andersevenrud** [comment] 2021-01-03 15:28
But why not add this to the user data in your authentication adapter ?

**Comment by miladhashemi** [comment] 2021-01-03 15:53
Unfortunately some sensitive data like `token` kept in swiftAuth that we want hide it from client side, if we put swiftAuth in user then it accessible from client,right!?

**Comment by andersevenrud** [comment] 2021-01-03 15:57
> if we put swiftAuth in user then it accessible from client,right!?

Yes.

But what I was asking about was: `I want to add project list to user session.`.


Example:

```
async login(req, res) {
  const result = await loginMyUser(req.body.username, req.body.password)
  req.session.swiftAuth = {}
  return result.profile // This should contain "project" etc.
}
```

**Comment by andersevenrud** [comment] 2021-01-03 16:14
I've published `@osjs/server@3.1.17` now. This makes it so you get a copy of the session data, not just `session.user`.

**Comment by miladhashemi** [comment] 2021-01-03 16:18
Yes, there are two kind data. The data that could be sent to client(like project list that uses as mountpoint name), we sent them to client with user session, but second type is data mist be kept and access from server, like token, expiration date,...

For this purpose we decide to separate these two key(user-swiftAuth)

**Comment by andersevenrud** [comment] 2021-01-03 16:20
Yes, I understand that, and that is totally fine.

My point is that you should *not* change this data outside of your authentication handler. Like what you mentioned by "I wat to add project list to user session". This all should ideally happen from within your adapter, not using the logged-in signal.

**Comment by miladhashemi** [comment] 2021-01-03 16:39
I agree with you. At first we were getting project list in login method.
But it had some shortages, first when we were implementing login method, we got project list(mountpoints) but actually these are two different operations. Secondly, we decide to decouple listing project list and login till a user decide uses only auth adapter, just install auth adapter to use openstack(tempAuth, keystone). And when users decide to get project list, they install swiftmountpoint ServiceProvider(server/client) to add mountpoints.

**Comment by andersevenrud** [comment] 2021-01-03 16:54
Okay then :smile: 

So this is resolved ? If so, please close the issue.

**Comment by miladhashemi** [comment] 2021-01-03 17:16
We have one issue yet 😬, for getting project list we need update session. First we need modify session and add project list to user session in server login signal, then use user updated session in client service provider to create mount points.
But you make session freeze, we can’t modify session 😕

**Comment by andersevenrud** [comment] 2021-01-03 17:31
Yes, you can't modify the session outside of the authentication adapter. This is by design. Sessions are only used in the life-cycle of HTTP requests.

In this case when this signal fires, and you execute some asynchronous function inside of the callback, then you will be outside of this life-cycle. Your operation has no guarantee of completing before the client has gotten a response from this HTTP request.

NB: Signals are not handled asynchronously!

There are methods in place to help you out with your de-coupling issue:


```javascript
const adapter = (core) => {
  const auther = core.make('my-login-service')

  return {
    async login(req, res) {
      const user = await auther.authenticate(req.body.username, req.body.password)
      const token = await auther.getToken(user)
      const result = {...user}

      if (core.has('my-other-service')) {
        const projects = await core.make('my-other-service').getProjects(user)
        result.projects = projects
      }

      req.session.token = token

      return result
  }
}
```

By the time the signal fires, your session is now complete. No need to mutate :smile:

**Comment by andersevenrud** [comment] 2021-01-03 17:50
In addition to this life-cycle, look at how the signal is implemented: https://github.com/os-js/osjs-server/blob/5ab0caf8e564ed9063d66b74dfa3c62557bf1cef/src/auth.js#L134

If you could somehow modify the session, it would not actually be saved and usable in future requests :nerd_face:

**Comment by miladhashemi** [comment] 2021-01-03 17:59
> Your operation has no guarantee of completing before the client has gotten a response from this HTTP request.

As I was describing scenario, I realized this issue :sweat_smile: , until your response I was thinking how I should solve this problem :grin:

Yesssss, You surprise me again. The **has()** method is extermlly helpful in these cases. :v:

**Comment by andersevenrud** [comment] 2021-01-03 18:04
> The has() method is extermlly helpful in these cases. :v: 

Great! I think this will solve your issue :blush: 

Let me know how it works out, and if it's all OK close this issue.

**Comment by miladhashemi** [comment] 2021-01-03 18:04
> If you could somehow modify the session, it would not actually be saved and usable in future requests. Also, it's a copy, not a reference

Only I was checked it where you send it call by value. Totally You remove call by reference for session. Just in HTTP request session could be modified :smiley:

**Closed** 2021-01-03 18:06 UTC
Labels: question
